networks:
  default:
    name: ${PROJECT_NAME}
    ipam:
      config:
        - subnet: ${SUBNET}

services:
  postgres:
    build: docker
    container_name: "${PROJECT_NAME}_postgres"
    ports:
      - "${LOCALHOST_POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASS}
      - POSTGRES_USER=${POSTGRES_DB_USER}
    volumes:
      - ${VOLUMES_DIR}/postgres:/var/lib/postgresql/data
      - ${VOLUMES_DIR}/backup:/backup
